# Generated by Django 6.0.6 on 2026-06-04 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Masculino', max_length=20)),
                ('peso_inicial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_inicial', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlCardiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('presion_sistolica', models.IntegerField()),
                ('presion_diastolica', models.IntegerField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('saturacion_oxigeno', models.IntegerField()),
                ('sintomas', models.TextField(blank=True, default='Ninguno')),
                ('diagnostico_ecg', models.CharField(default='Pendiente', max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_controles', to='pacientes.paciente')),
            ],
        ),
    ]
