# Generated by Django 6.0.6 on 2026-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcardiologico',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos_medicos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='controlcardiologico',
            name='consentimiento_firmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlcardiologico',
            name='disnea',
            field=models.BooleanField(default=False, help_text='Falta de aire'),
        ),
        migrations.AddField(
            model_name='controlcardiologico',
            name='dolor_pecho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlcardiologico',
            name='edema',
            field=models.BooleanField(default=False, help_text='Hinchazón en piernas'),
        ),
        migrations.AddField(
            model_name='controlcardiologico',
            name='evolucion',
            field=models.TextField(blank=True, help_text='Notas libres de evolución del paciente', null=True),
        ),
        migrations.AddField(
            model_name='controlcardiologico',
            name='mareos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlcardiologico',
            name='plan_medicacion',
            field=models.TextField(blank=True, help_text='Fármaco, dosis y frecuencia', null=True),
        ),
        migrations.AddField(
            model_name='controlcardiologico',
            name='proxima_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, default='Ninguna', help_text='Alergias a medicamentos o materiales'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_base',
            field=models.TextField(blank=True, default='Ninguno', help_text='Ej: Diabetes, Hipertensión, etc.'),
        ),
    ]
