# Generated by Django 6.0.6 on 2026-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_controlcardiologico_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pacientes/'),
        ),
    ]
