# Generated by Django 6.0.6 on 2026-06-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_seed_test_patients'),
        ('pacientes', '0005_paciente_foto'),
    ]

    operations = [
    ]
