# Generated by Django 6.0.6 on 2026-06-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_historialclinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
