# Generated by Django 6.0.6 on 2026-06-06 03:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_historialclinico_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arritmia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_arritmia', models.CharField(max_length=100)),
                ('fecha_deteccion', models.DateField()),
                ('nivel_riesgo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arritmias_detectadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arritmias', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Arritmia',
                'verbose_name_plural': 'Arritmias',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoArritmia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_control', models.DateField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('nivel_riesgo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arritmia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='pacientes.arritmia')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_arritmias_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Arritmia',
                'verbose_name_plural': 'Seguimientos de Arritmias',
                'ordering': ['-fecha_control'],
            },
        ),
    ]
