# Generated by Django 6.0.5 on 2026-06-06 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_arritmia_seguimientoarritmia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_examen', models.CharField(choices=[('ECG', 'Electrocardiograma'), ('HOLTER', 'Holter'), ('ECOCARDIOGRAMA', 'Ecocardiograma'), ('INFORME_CARDIOLOGICO', 'Informe Cardiológico'), ('OTRO', 'Otro')], max_length=50)),
                ('fecha_examen', models.DateField()),
                ('resultado', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='examenes_medicos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_registrados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_medicos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Examen Médico',
                'verbose_name_plural': 'Exámenes Médicos',
                'ordering': ['-fecha_examen'],
            },
        ),
    ]
