# Generated by Django 6.0.5 on 2026-05-08 22:03

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    roles = ['superadmin', 'administrador', 'doctor', 'paciente']
    for role_name in roles:
        Role.objects.get_or_create(nombre=role_name)

def remove_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    roles = ['superadmin', 'administrador', 'doctor', 'paciente']
    Role.objects.filter(nombre__in=roles).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles, remove_roles),
    ]
