# Generated by Django 6.0.5 on 2026-05-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
